from config import *

levels = [
	{
		"n": 1.1,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"random_maze": True,
		"char_health": 100,
	},
	{
		"n": 1.2,
		"num_enemies": 0,
		"theme": "modern1",
		"music": "inspire",
		"time_limit": 30,
		"spiral_maze": True,
		"char_health": None,
		"target": 'reach-finish-30-sec',
		"has_finish": True,
	},
	{
		"n": 1.3,
		"num_enemies": 5,
		"theme": "classic",
		"music": "playful_sparrow",
		"random_maze": True,
		"four_rooms": True,
		"char_health": 200,
	},
	{
		"n": 1.4,
		"num_enemies": 20,
		"theme": "classic",
		"music": "valiant_warriors",
		"time_limit": 60,
		"char_health": 250,
		"target": 'kill-all-1-min',
		"bg_image": "bg/stonehenge.jpg",
		"cloud_mode": True,
	},
	{
		"n": 2.1,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"random_maze": True,
		"gate_puzzle": True,
		"num_gate_puzzle_gates": 2,
		"num_gate_puzzle_plates": 2,
		"target": "reach-finish",
		"char_health": 100,
	},
	{
		"n": 2.2,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"random_maze": True,
		"gate_puzzle": True,
		"num_gate_puzzle_gates": 4,
		"num_gate_puzzle_plates": 4,
		"target": "reach-finish",
		"char_health": 100,
	},
	{
		"n": 2.3,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"spiral_maze": True,
		"gate_puzzle": True,
		"num_gate_puzzle_gates": 6,
		"num_gate_puzzle_plates": 4,
		"target": "reach-finish",
		"char_health": 100,
		"cloud_mode": True,
	},
	{
		"n": 3.1,
		"num_enemies": 0,
		"theme": "modern1",
		"music": "adventures",
		"four_rooms": True,
		"color_puzzle_values": 2,
		"color_puzzle": True,
		"char_health": None,
		"target": 'complete-color-puzzle-green',
	},
	{
		"n": 3.2,
		"num_enemies": 5,
		"theme": "modern1",
		"music": "valiant_warriors",
		"color_puzzle_values": 4,
		"color_puzzle_size": (9, 9),
		"color_puzzle": True,
		"time_limit": 60,
		"char_health": 100,
		"target": 'complete-color-puzzle-green',
	},
	{
		"n": 3.3,
		"num_enemies": 5,
		"theme": "modern1",
		"music": "adventures",
		"color_puzzle_values": 6,
		"color_puzzle_size": (11, 11),
		"color_puzzle": True,
		"time_limit": 120,
		"char_health": 100,
		"target": 'complete-color-puzzle-green',
	},
	{
		"n": 4.1,
		"num_enemies": 3,
		"num_barrels": 2,
		"theme": "modern2",
		"music": "breath",
		"barrel_puzzle": True,
		"char_health": 100,
		"target": 'complete-barrel-puzzle',
	},
	{
		"n": 4.2,
		"num_enemies": 5,
		"num_barrels": 5,
		"theme": "modern2",
		"music": "breath",
		"barrel_puzzle": True,
		"char_health": 100,
		"target": 'complete-barrel-puzzle',
	},
	{
		"n": 4.3,
		"num_enemies": 7,
		"num_barrels": 7,
		"theme": "modern2",
		"music": "breath",
		"barrel_puzzle": True,
		"char_health": 150,
		"target": 'complete-barrel-puzzle',
	},
	{
		"n": 5.1,
		"num_enemies": 3,
		"theme": "ancient1",
		"music": "breath",
		"random_maze": True,
		"lock_puzzle": True,
		"min_locks": 2,
		"max_locks": 3,
		"char_health": 100,
		"target": "reach-finish",
	},
	{
		"n": 5.2,
		"num_enemies": 5,
		"theme": "ancient1",
		"music": "breath",
		"random_maze": True,
		"lock_puzzle": True,
		"min_locks": 3,
		"max_locks": 5,
		"char_health": 100,
		"target": "reach-finish",
	},
	{
		"n": 5.3,
		"theme": "ancient1",
		"music": "breath",
		"lock_puzzle": True,
		"random_maze": True,
		"min_locks": 5,
		"max_locks": 7,
		"enemy_key_drop": True,
		"char_health": 150,
		"target": "reach-finish",
	},
	{
		"n": 6.1,
		"theme": "modern1",
		"music": "epic_cinematic_trailer",
		"memory_puzzle": True,
		"memory_puzzle_size": (5, 3),
		"memory_puzzle_reveal_time": 10,
		"num_enemies": 0,
		"char_health": None,
		"target": "complete-memory-puzzle",
	},
	{
		"n": 6.2,
		"theme": "stoneage1",
		"music": "stoneage/08_the_golden_valley",
		"memory_puzzle": True,
		"memory_puzzle_size": (3, 4),
		"has_start": True,
		"has_finish": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "complete-memory-puzzle",
	},
	{
		"n": 6.3,
		"theme": "classic",
		"music": "epic_cinematic_trailer",
		"memory_puzzle": True,
		"four_rooms": True,
		"num_enemies": 2,
		"char_health": 100,
		"target": "complete-memory-puzzle",
	},
	{
		"n": 6.4,
		"theme": "ancient1",
		"music": "warfare",
		"memory_puzzle": True,
		"memory_puzzle_size": (3, 3),
		"memory_puzzle_reveal_time": 8,
		"nine_rooms": True,
		"time_limit": 150,
		"num_enemies": 0,
		"char_health": None,
		"target": "complete-memory-puzzle",
	},
	{
		"n": 6.5,
		"theme": "moss",
		"music": "forest_walk",
		"memory_puzzle": True,
		"memory_puzzle_revealed": True,
		"num_enemies": 0,
		"time_limit": 300,
		"char_health": None,
		"target": "complete-memory-puzzle-revealed-5-min",
	},
	{
		"n": 7.1,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"fifteen_puzzle": True,
		"fifteen_puzzle_size": (3, 2),
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-fifteen-puzzle",
	},
	{
		"n": 7.2,
		"theme": "moss",
		"music": "forest_walk",
		"fifteen_puzzle": True,
		"nine_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-fifteen-puzzle",
	},
	{
		"n": 7.3,
		"theme": "stoneage1",
		"music": "film",
		"fifteen_puzzle": True,
		"fifteen_puzzle_size": (4, 4),
		"four_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-fifteen-puzzle",
	},
	{
		"n": 7.4,
		"theme": "stoneage2",
		"music": "stoneage/08_the_golden_valley.mp3",
		"fifteen_puzzle": True,
		"fifteen_puzzle_size": (7, 7),
		"num_enemies": 15,
		"char_health": 200,
		"has_start": True,
		"has_finish": True,
		"target": "solve-fifteen-puzzle",
	},
	{
		"n": 8.1,
		"theme": "default",
		"music": "forest_walk",
		"rotatepic_puzzle": True,
		"rotatepic_puzzle_size": (8, 8),
		"bg_image": "pictures/danik-lion-motocycle.jpg",
		"bg_image_crop": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-rotatepic-puzzle",
	},
	{
		"n": 8.2,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"rotatepic_puzzle": True,
		"rotatepic_puzzle_size": (7, 7),
		"rotatepic_puzzle_image": "pictures/danik-lion-irisha-square.jpg",
		"has_start": True,
		"has_finish": True,
		"num_enemies": 10,
		"char_health": 150,
		"target": "solve-rotatepic-puzzle",
	},
	{
		"n": 8.3,
		"theme": "default",
		"music": "forest_walk",
		"rotatepic_puzzle": True,
		"rotatepic_puzzle_image": "pictures/danik-lego-tiger.jpg",
		"rotatepic_puzzle_image_crop": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-rotatepic-puzzle",
	},
	{
		"n": 8.4,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"rotatepic_puzzle": True,
		"rotatepic_puzzle_size": (9, 9),
		"bg_image": "pictures/danik-lion-irisha-cafe.jpg",
#		"bg_image_crop": True,
		"num_enemies": 0,
		"char_health": None,
		"target": "solve-rotatepic-puzzle",
	},
	{
		"n": 9.1,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"portal_puzzle": True,
		"portal_puzzle_num_portals_per_hall": 2,
		"num_enemies": 0,
		"char_health": None,
		"target": "reach-finish",
	},
	{
		"n": 9.2,
		"theme": "stoneage2",
		"music": "stoneage/08_the_golden_valley.mp3",
		"portal_puzzle": True,
		"portal_puzzle_num_portals_per_hall": 3,
		"has_start": True,
		"has_finish": True,
		"num_enemies": 5,
		"char_health": 100,
		"target": "reach-finish",
	},
	{
		"n": 9.3,
		"theme": "moss",
		"music": "forest_walk",
		"portal_puzzle": True,
		"num_enemies": 10,
		"char_health": 150,
		"target": "reach-finish",
	},
	{
		"n": 10.1,
		"theme": "stoneage1",
		"music": "stoneage/01_stardust_falling",
		"stoneage_puzzle": True,
		"bg_image": "bg/remains_of_a_threat.jpg",
		"char_health": 100,
		"target": "reach-finish",
	},
	{
		"n": 11.1,
		"theme": "stoneage1",
		"music": "stoneage/08_the_golden_valley.mp3",
		"trivial_puzzle": True,
		"char_health": 40,
		"target": "reach-finish",
	},
]
