#!/bin/sh

PATH=$PATH:`dirname $0`

update-readme-md
create-html-elements-index
create-html-elements-authors
create-html-elements-puzzles
create-html-elements-themes

create-html-page index
create-html-page download
create-html-page resources
create-html-page authors

for puzzle_element_filename in elements/puzzles/*.html; do
	page_name=`echo $puzzle_element_filename | cut -d/ -f2- | cut -d. -f1`
	create-html-page $page_name
done

for theme_element_filename in elements/themes/*.html; do
	page_name=`echo $theme_element_filename | cut -d/ -f2- | cut -d. -f1`
	create-html-page $page_name
done

create-html-page tutorial/index

# The optional script sync-html-pages-to-webserver if present may look like:
# rsync -av --copy-unsafe-links html/ "$HTML_ROOT"/
if /bin/which sync-html-pages-to-webserver >/dev/null 2>&1; then
	sync-html-pages-to-webserver
fi
