#!/usr/bin/python

import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from filetools import RegenerateFile, get_dir_names

# create elements/themes/index.html
# create elements/sidebars/themes.html
# create elements/themes/<theme-name>.html for each <theme-name>

ext = '.png'
all_names = get_dir_names("images/default", ext)

def start_table(file): 
	file.print('<script>function toggle_zoom() { elem = document.getElementById("img-table"); elem.className = elem.className == "img-table-half" ? "img-table-full" : "img-table-half" }</script>')
	file.print('<table id="img-table" class="img-table-half">')
	file.write('<tr>')
	file.write('<th class="zoom"><a href="javascript:toggle_zoom()">🔍</a></th>')
	for name in all_names:
		file.write('<th title="%s">%s</th>' % (name, name))
	file.print("</tr>")

file_eti = RegenerateFile("elements/themes/index.html")
file_eti.print('<h1>Themes</h1>\n')
start_table(file_eti)

file_est = RegenerateFile("elements/sidebars/themes.html")
file_est.print('<a href="themes/index.html"><button class="page<{ current-page IF pagename themes/index}>">All Themes</button></a>')

for theme in sorted([name for name in os.listdir("images") if os.path.isdir("images/%s" % name)]):
	file_eti.write('<tr>')
	file_eti.write('<th><a href="themes/%s.html" title="%s">%s</a></th>' % (theme, theme, theme))

	file_est.print('<a href="themes/%s.html"><button class="page<{ current-page IF pagename themes/%s}>"> %s </button></a>' % (theme, theme, theme))

	file_et1 = RegenerateFile("elements/themes/%s.html" % theme)
	file_et1.print('<h1>Theme %s</h1>' % theme)
	start_table(file_et1)
	own_row = '<tr>'
	act_row = '<tr>'
	own_row += '<th>own</th>'
	act_row += '<th>actual</th>'
	names = get_dir_names('images/' + theme, ext)
	for name in all_names:
		file_eti.write('<td>')
		own_row += '<td>'
		act_row += '<td>'
		own_img_html = '<img title="%s" src="images/%s/%s%s">' % (name, theme, name, ext)
		if name in names:
			file_eti.write(own_img_html)
			own_row += own_img_html
			act_row += own_img_html
		else:
			file_eti.write('-')
			own_row += '-'
			act_row += '<img title="%s" src="images/default/%s%s">' % (name, name, ext)
		own_row += '</td>'
		act_row += '</td>'
		file_eti.write('</td>')
	own_row += '</tr>'
	act_row += '</tr>'
	file_et1.print(own_row)
	file_et1.print(act_row)
	file_et1.print('</table>')
	file_et1.finalize()

	file_eti.print('</tr>')

file_eti.print('</table>')
file_eti.finalize()

file_est.finalize()
