#!/usr/bin/python
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from filetools import RegenerateFile

# read AUTHORS file line by line
# create elements/authors.html

filename = "AUTHORS"

file_r = open(filename, "r")
if not file_r:
	print("Can't open file %s for reading" % filename)
	exit(1)

file_w = RegenerateFile("elements/authors.html")
file_w.print('<h1>Authors</h1>')

is_new_author = True
description = ""
while True:
	line = file_r.readline()
	is_eof = line == ""
	if line == "\n" or is_eof and description != "":
		if description == "":
			continue
		file_w.print("<p>\n%s</p>" % description)
		is_new_author = True
		description = ""
	elif is_eof:
		break
	elif is_new_author:
		file_w.print("<h2>%s</h2>" % line.rstrip(': \t\r\n'))
		is_new_author = False
	else:
		description += line

file_r.close()
file_w.finalize()
