#!/usr/bin/python

import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from filetools import RegenerateFile
from puzzleinfo import get_all_puzzleinfo_objects

# create elements/puzzles/index.html
# create elements/sidebars/puzzles.html
# create elements/puzzles/<puzzle-name>.html for each <puzzle-name>

file_epi = RegenerateFile("elements/puzzles/index.html")
file_epi.print('<h1>Puzzles</h1>\n')

file_esp = RegenerateFile("elements/sidebars/puzzles.html")
file_esp.print('<a href="puzzles/index.html"><button class="page<{ current-page IF pagename puzzles/index}>">All Puzzles</button></a>')

for info in get_all_puzzleinfo_objects():
	html = info.get_html()
	file_ep1 = RegenerateFile("elements/puzzles/%s.html" % info.name)
	file_ep1.print(html)
	file_ep1.finalize()

	file_epi.print(html.replace("h1>", "h2>"))
	file_epi.print('')

	file_esp.print('<a href="puzzles/%s.html"><button class="page<{ current-page IF pagename puzzles/%s}>">%s</button></a>' % (info.name, info.name, info.name))

file_epi.finalize()

file_esp.finalize()
