#!/usr/bin/python

import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from filetools import RegenerateFile
from puzzleinfo import get_all_puzzleinfo_objects

hypertext = ""
for info in get_all_puzzleinfo_objects():
	hypertext += info.get_hypertext()

filename = "README.md"

file_r = open(filename, "r")
if not file_r:
	print("Can't open file %s for reading" % filename)
	exit(1)

file_w = RegenerateFile(filename)

skip_line = False
while line := file_r.readline():
	if skip_line and line.startswith("## "):
		skip_line = False
	if not skip_line:
		file_w.write(line)
	if line == "## Puzzles\n":
		skip_line = True
		file_w.write('\n')
		file_w.write(hypertext)

file_r.close()
file_w.finalize()
